### ISSUE TITLE
ToDo 

### ISSUE THREAD

**Issue by easazade** [6thsolution/fantom#11]
- [ ] add header parser to parse and generate header parameters for api methods
- [ ] add support for methods that require multipart request bodies. (beware of issue with `MultiPart.fromFile()` not working in the web)
- [ ] test uploading files (50 MB+) on the web & check if it crashes. fix if there is any issues
- [ ]  use compute or similar approach to deserialize large response bodies
- [ ] add custom body to to generated types for `RequestBodies` 
- [ ] add exception handling (needs discussion)
- [ ] remove using `dart_sealed` in the benefit of having simpler generated types. (this'll take time)
- [ ] get the version 3 openapi specs of city and test fantom on that
